### ISSUE TITLE
スキル入力画面の作成

### ISSUE THREAD

**Issue by sunamoto-mikiya** [sunamoto-mikiya/oceans3#3]
- セレクトボックスで言語の選択(言語選択画面はtopa'z参考に)
- セレクトボックスで各言語のレベル選択

以下個人的願望
githubのリンク張ってコミット数取ってきたい

登録処理
https://github.com/sunamoto-mikiya/oceans1/issues/3#issue-1377566604

**Comment by ryuichi-maeda** [comment]
基本的な実装完了
以下は時間があればやる
> 以下個人的願望
githubのリンク張ってコミット数取ってきたい
